# Generated by Django 4.2.1 on 2023-05-28 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callCenter', '0002_rename_employee_worker_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
