# Generated by Django 4.2.1 on 2023-05-28 21:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('callCenter', '0003_remove_customer_phone_number_customer_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='callqueue',
            old_name='caller',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='chatroom',
            old_name='caller',
            new_name='customer',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='employee_id',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='callCenter.worker'),
        ),
        migrations.AddField(
            model_name='worker',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
                ('sender_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='callCenter.chatroom')),
            ],
        ),
    ]
