# Generated by Django 4.2.1 on 2023-05-29 01:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('callCenter', '0004_rename_caller_callqueue_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='callCenter.customer'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='worker',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
